AWSTemplateFormatVersion: 2010-09-09
Description: 'Section 1 activity template - AWS CloudFormation Step by Step: Beginner to Intermediate'

#Define variáveis para serem usadas ao longo do YML
Parameters:
  DBName:
    Type: String
    Default: gabriel-taveira-db

  DBUsername:
    Type: String
    Default: dbadmin

  DBPassword:
    Type: String
    Default: mystrongpassword

#Define recursos que vão ser criados pelo CloudFormation
Resources:
  SampleTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DBName
      AttributeDefinitions:
        - 
          AttributeName: id
          AttributeType: S
      KeySchema:
        - 
          AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  SampleRDSInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    Properties:
      Engine: mariadb
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: !Ref DBName
      MultiAZ: false
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      AllocatedStorage: 8
      StorageType: gp2
      BackupRetentionPeriod: 0
    

      